### ISSUE TITLE
Initial push notifications specs

### ISSUE THREAD

**Issue by elmigranto** [j3k0/ganomede-notifications#14]
Adding token to database. What's an actual endpoint and body payload.
We're using redis. (Don't forget about prefixing stuff with module name!)

What would the scenarios of sending out notifications be, "To all iOS users", "To all users who played game X on iOS", "To all users who played game X", "To certain username"?

**Comment by elmigranto** [comment]
I assume tokens are unique per `username + device + game app`, but we will have same ganomede account for different apps on multiple devices.

**Comment by j3k0** [comment]
Multiple tokens for each `[ username, game ]`

Each token: `{ "type": "ios", "value": "1b193i129i" }`

A single user may be playing from multiple ios device, or multiple android devices.

**Comment by j3k0** [comment]
Scenarios:
- It's now your turn to play
- Invitation received

Those are events already received by the notifications module. A subset of them need to be sent via push notifications. Notification to be "pushed" will contain the following extra field:

```
"push": {
  "message": "It's your turn to play"
}
```

**Comment by elmigranto** [comment]
So we will only send notifications to single user in particular game app (which may include multiple devices and multiple operating systems)?

**Comment by elmigranto** [comment]
Since we required to check for token uniqueness, I suggest we use redis sets with keys `prefix:username:app-name` with values like `operating-system:value` if there will be no other fields in token. Something like:

`notifications/v1:push-tokens:alice:substract-game/v1`: `(ios:deadbeef, android:abcde123)`
(Do we include versions?)

**Comment by j3k0** [comment]
Yes. Single user, multiple devices.

Suggestion approved. Better without versions, as same database should be usable with future versions of the module.

**Comment by elmigranto** [comment]
See #25 for more on this.
