### ISSUE TITLE
Interaction with Coordinator module

### ISSUE THREAD

**Issue by elmigranto** [j3k0/ganomede-notifications#20]
PR: #21

**Comment by elmigranto** [comment]
We'll have 2 types of notifications:
- `leave` — someone left a game;
- `join` — someone joined a game.

Both will have common `notification.data`: 

```
{ "game": {
    "id": String
    "type": String
    "players": [String]
  }

  "player": String  // username of a person who left/joined
  "reason": String  // not sure, "resign" for leave, what about joininng?
}
```

**Comment by j3k0** [comment]
That's it. There's no `reason` for `join`, and it's optional for `leave`.

**Comment by elmigranto** [comment]
Closing this, #21 is ready.
