### ISSUE TITLE
Google Cloud Messaging (GCM) support

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-notifications#23]
I don't remember exactly the state of this.
1. We need to be able to register gcm tokens;
2. Push-worker needs to send push notification using gcm when there are some;

**Comment by elmigranto** [comment]
> 1. We need to be able to register gcm tokens;

This [works](https://github.com/j3k0/ganomede-notifications#save-push-token-post-authauthtokenpush-token) as long as token's a string and `type` is `'gcm'`.

> 1. Push-worker needs to send push notification using gcm when there are some;

This is missing.

**Comment by j3k0** [comment]
Ok, so this is needed.
