### ISSUE TITLE
Cleaning up old messages

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-notifications#27]
The push worker seems to have failed a few days ago. The database is filled with millions of meaningless messages. Is there a way to clean up messages? (only messages, not tokens).

If you have time, this is kinda urgent 🆘

**Comment by elmigranto** [comment]
Do you mean that process died and there are a bunch of out-of-date notifications?

**Comment by elmigranto** [comment]
The list of notifications to send is at key `config.pushApi.notificationsPrefix`, you can:
- [`DEL`](http://redis.io/commands/DEL) the list all together;
- [`LTRIM`](http://redis.io/commands/ltrim) the list so it only contains X most recent notifications.

**Comment by j3k0** [comment]
Not sure what happened. I've been said notifications stopped working a few days ago. Indeed, when starting the push-worker, he is processing messages dating from last wednesday.

**Comment by elmigranto** [comment]
Looks like messages are added to the head of the list and processed from the tail. So `LTRIM 0 1000`, for example, will leave you with 1000 latest notifications.

**upd**: it is 100**1**, not 1000.

**Comment by j3k0** [comment]
Thanks.

For future reference:

```
redis-cli ltrim notifications:push-notifications 0 1000
```
