### ISSUE TITLE
Use ganomede client library for testing and integration

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-notifications#4]
You can find it here:
https://github.com/j3k0/ganomede-client/releases/tag/v0.1.0

And test/example here:
https://github.com/j3k0/ganomede-client/blob/master/src-js/test.js

Specifically the part about notifications:
https://github.com/j3k0/ganomede-client/blob/master/src-js/test.js#L93-L119

Think it'll make things easier if I publish on npm? Probably yes

**Comment by elmigranto** [comment]
> publish on npm

Surely won't hurt if this will be `npm install`able!
I believe `npm` can install git repos by tag, but this won't give version matching and whatnot, and I figured the goal is to make it accessible on npm anyway.

**Comment by j3k0** [comment]
Ok, in the meantime I just found out a small bug (in the `listenTo` part, not the part sending notifications). I will fix that tomorrow morning and publish, I will let you know.

**Comment by j3k0** [comment]
Npm-published under name `ganomede`

https://www.npmjs.com/package/ganomede

**Comment by j3k0** [comment]
@elmigranto See https://github.com/j3k0/ganomede-doco-deploy for deploying a full ganomede stack.
