### ISSUE TITLE
Interaction with Turngame module

### ISSUE THREAD

**Issue by elmigranto** [j3k0/ganomede-notifications#9]
What data and notification types do we need for Turngame? What should they include as data?
Relevant pull request: https://github.com/j3k0/ganomede-notifications/pull/10
1. move is perfromed (at least should include game ID)

**Comment by j3k0** [comment]
Basically, we need to know that a move has been performed on a given game.

All participant, except the one making the move, will be notified.

Invitation data will look like this:

``` js
"from": "turngame/v1",
"to": "username",
"type": "move",
"data": {
  "game": {
    "id": "ab12345789",
    "type": "triominos/v1",
    "players": [ "some_username_1", "some_username_2" ],
    "turn": "some_username_1",
    "status": "active",
    "gameData": { ... }
  }
}
```
